version: '2'
services:
    data-flow-server:
        image: springcloud/spring-cloud-dataflow-server-kubernetes
  # last gateway server run
 # server-gateway:
 #   build: ./Shooter-GateWay
 #   ports:
 #   - 9001:9001
 #   depends_on:
 #   - server-discovery
 #   environment:
 #       - "SPRING_PROFILES_ACTIVE=docker"

#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#    - 15672:15672
#    environment:
#    - RABBITMQ_DEFAULT_USER=test
#    - RABBITMQ_DEFAULT_PASS=test
#    - RABBITMQ_DEFAULT_VHOST=/test
